### ISSUE TITLE
Getting wrong number of files on larger date range

### ISSUE THREAD

**Issue by Ishank09** [uw-echospace/ooi-workflow#1]
If given any date other than the one shown in the image, the number of files is incorrect.

<img width="1028" alt="image" src="https://github.com/uw-echospace/ooi-workflow/assets/23238187/3d17b2db-acf5-48cd-89b1-9fa0d629acb1">

When inputting the start date and end date as:
start_datetime = dt.datetime(2016, 8, 21, 0, 0)
end_datetime = dt.datetime(2017, 8, 22, 0, 0)

the number of raw files coming is 2. This is incorrect, as monthly files were around 30.

Need to check the logic for getting files from the server.

**Comment by sagnikgh1899** [comment]
Fixed the logic for getting the correct number of files for any given date range. See commit: https://github.com/uw-echospace/ooi-workflow/commit/5ceb7128eafbd7c2ad41a3e909368c44213d3d0d
