### ISSUE TITLE
Combine Echodata - Batch Processing

### ISSUE THREAD

**Issue by prerit162** [uw-echospace/ooi-workflow#6]
[Data_Fetch.zip](https://github.com/uw-echospace/ooi-workflow/files/14230391/Data_Fetch.zip)
<img width="578" alt="Batch processing - Combine Echodata" src="https://github.com/uw-echospace/ooi-workflow/assets/118493234/6e300c17-51c0-4826-89f1-c0e64fa52b59">

**Comment by leewujung** [comment]
I suggest that you upload the notebook to be a [gist](https://gist.github.com/) or push up the notebook. The image does not give enough info about what's going on.

**Comment by prerit162** [comment]
I have added the notebook as a zip file. Let me know if you are able to access it else I will push it
