### ISSUE TITLE
Combine Echodata 

### ISSUE THREAD

**Issue by prerit162** [uw-echospace/ooi-workflow#7]
[Data_Fetch.zip](https://github.com/uw-echospace/ooi-workflow/files/14230393/Data_Fetch.zip)
<img width="378" alt="Combine_Echodata" src="https://github.com/uw-echospace/ooi-workflow/assets/118493234/51b2be0a-9b30-4fba-b186-30ad4751e9db">

**Comment by leewujung** [comment]
I suggest that you upload the notebook to be a [gist](https://gist.github.com/) or push up the notebook. The image does not give enough info about what's going on.

**Comment by prerit162** [comment]
I have added the notebook as a zip file. Let me know if you are able to access it else I will push it

**Comment by leewujung** [comment]
Please upload it as a gist.
